---
- name: Deploy to staging server
  hosts: sandbox
  become: yes
  remote_user: samsul
  become_user: root
  gather_facts: no
  vars:
    deploy_to: /var/www/vhosts/dev.dot.co.id/dot-intern-registration
    git_repo: git@gitlab.com:pt-dot-internal/dot-intern-registration.git
    git_branch: develop
    git_identity_key: /var/www/.ssh/id_rsa
    php_path: /usr/bin/php
    composer_path: /usr/bin/composer
    apache_runas: www-data
  
  tasks:
  - name: Update remote repository using SSH key
    git:
      repo: "{{ git_repo }}"
      dest: "{{ deploy_to }}"
      version: "{{ git_branch }}"
      accept_hostkey: true
      update: yes
      force: yes
      key_file: "{{ git_identity_key }}"
    when: git_identity_key|trim != ''

  - name: Running composer install
    shell: chdir={{ deploy_to }} 
      {{ composer_path }} install --no-plugins --no-scripts

  - name: Running composer dump-autoload
    shell: chdir={{ deploy_to }} 
      {{ composer_path }} dump-autoload

  - name: List artisan commands
    shell: chdir={{ deploy_to }}
      {{ php_path }} artisan
    register: artisan_commands

  - name: Run multiple artisan command
    shell: chdir={{ deploy_to }}
      {{ php_path }} artisan {{ item }}
    with_items: 
      - key:generate
      - migrate
      #- db:seed
      - config:clear
      - cache:clear
    ignore_errors: no

  - name: update ownership 
    file: 
      path: "{{ deploy_to }}"
      state: directory 
      recurse: yes 
      group: "{{ apache_runas }}"
      owner: "{{ apache_runas }}"
